server:
  port: 8080

spring:
  application:
    name: static-llm
  quartz:
    job-store-type: memory # 暂时使用内存存储，生产环境建议用 jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5

spotbugs:
  jar-path: D:\CodeDetectTool\spotbugs-4.9.8\lib\spotbugs.jar
  report-dir: D:\CodeDetectTool\reports\

llm:
  provider: deepseek
  deepseek:
    api-key: sk-058260311f7f4456843c0ab797ccde44
    base-url: https://api.deepseek.com
    model: deepseek-chat

logging:
  level:
    bupt.staticllm: info
